stages:
  - init
  - test
  - tag_deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds\

# Set environment vars
before_script:
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

pip-install:
  stage: init
  when: always
  script:
    - python -m venv --clear %VENV_ROOT%%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
    - call %VENV_ROOT%%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - pip install --upgrade pip
    - pip install wafer_map
    - pip install build-reqs/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl
    - pip install build-reqs/douglib-1.0.10-py3-none-any.whl
    - pip install green
    - pip install colour

tests:
  stage: test
  when: on_success
  script:
    - call %VENV_ROOT%%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
#    - green -vvv -s 1 gdwcalc
    - python -m unittest -v gdwcalc\tests\test_gdwcalc.py

tag_bundle:
  stage: tag_deploy
  when: on_success
  only:
    - tags
  script:
    - call %VENV_ROOT%%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python build_exe.py build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - build/exe.win-amd64-3.4/
      - dist/*.whl

clean-up:
  stage: cleanup
  when: always
  script:
    - rd /S /Q %VENV_ROOT%%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
