stages:
  - init
  - test
  - tag_deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds

# Set environment vars
before_script:
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

pip-install:
  stage: init
  when: always
  script:
    - echo Creating venv at `%VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%`
    - python -m venv --clear %VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
    - call %VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    # Can't upgrade pip in place.
    # See https://github.com/pypa/pip/issues/1299#issuecomment-188198496
    - python -m pip install pip==8.1.0 --no-cache-dir
    - pip install wafer_map --no-cache-dir
    - pip install build-reqs/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl
    - pip install green --no-cache-dir
    - pip install colour --no-cache-dir
    - pip install numpy --no-cache-dir
#    - pip install hypothesis

tests:
  stage: test
  when: on_success
  script:
    - call %VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python -m green -vvv -s 1 -W gdwcalc

tag_bundle:
  stage: tag_deploy
  when: on_success
  only:
    - tags
  script:
    - call %VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python build_exe.py build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - build/exe.win-amd64-3.4/
      - dist/*.whl

clean-up:
  stage: cleanup
  when: always
  script:
    - rd /S /Q %VENV_ROOT%\python34_x64\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
