stages:
  - init
  - test
  - tag_deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds
  VENV_PY34: C:\temp\builds\python34_x64
  WXPYTHON_SNAPSHOTS: https://wxpython.org/Phoenix/snapshot-builds
  PYPI_URL: http://tphweb.tph.local/pypi

# Set environment vars
before_script:
  - REM ==================== Before Script ====================
  - echo %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

  # Clear pip cache because it sometimes causes issues.
  - rd /S /Q C:\Users\tph-buildbot\AppData\Local\pip\Cache
  - REM ~~~~~~~~~~~~~~~~~~~~ End Before Script ~~~~~~~~~~~~~~~~~~~~

pip-install:
  stage: init
  when: always
  tags:
    - python
  script:
    - REM ==================== pip-install ====================
    - python -m venv --clear %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    # Can't upgrade pip in place.
    # See https://github.com/pypa/pip/issues/1299#issuecomment-188198496
    - python -m pip install --upgrade --no-cache-dir pip
    - python -m pip install --no-cache-dir wheel
    - "python -m pip install --only-binary :all: --pre -f %WXPYTHON_SNAPSHOTS% wxPython_Phoenix"
    - python -m pip install --no-cache-dir -r requirements.txt

tests:
  stage: test
  when: on_success
  tags:
    - python
  script:
    - REM ==================== tests ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python -m pip install --no-cache-dir -r dev-requirements.txt
    - python -m green -vvv -s 1 -W -t gdwcalc

tag_bundle:
  stage: tag_deploy
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - REM ==================== build-exe ====================
    - call %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%\Scripts\activate.bat
    - python build_exe.py build
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - build/exe.win-amd64-3.4/
      - dist/*.whl

clean-up:
  stage: cleanup
  when: always
  tags:
    - python
  script:
    - REM ==================== clean-up ====================
    - rd /S /Q %VENV_PY34%\%CI_PROJECT_ID%__%CI_BUILD_REF_NAME%
