stages:
  - init
#  - test
  - deploy
  - cleanup

before_script:
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

pip-install:
  stage: init
  when: always
  script:
    - pip install wafer_map
    - pip install build-reqs/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl
    - pip install build-reqs/douglib-1.0.10-py3-none-any.whl

# Run the test(s)
#tests:
#  stage: test
#  when: on_success
#  script:
#    - echo Not testing

bundle:
  stage: deploy
  when: on_success
  script:
    - python build_exe.py build
    - python setup.py sdist bdist_wheel
  artifacts:
    only:
      - tags
    paths:
      - build/exe.win-amd64-3.4/
      - dist/*.whl

clean-up:
  stage: cleanup
  when: always
  script:
    - pip uninstall wafer_map -y
    - pip uninstall wxPython-Phoenix -y
    - pip uninstall douglib -y
