stages:
  - init
  - test
  - cleanup
  - tag_init
  - tag_deploy
  - tag_cleanup

# Set environment vars
before_script:
  - call C:\WinPython34\scripts\env.bat
  - python -c "import sys;print(sys.version)"

pip-install:
  stage: init
  when: always
  only:
    - master
  script:
    - pip install wafer_map
    - pip install build-reqs/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl
    - pip install build-reqs/douglib-1.0.10-py3-none-any.whl
    - pip install green

tests:
  stage: test
  when: on_success
  only:
     - master
  script:
    - green -vvv gdwcalc

clean-up:
  stage: cleanup
  when: always
  only:
    - master
  script:
    - pip uninstall wafer_map -y
    - pip uninstall wxPython-Phoenix -y
    - pip uninstall douglib -y
    - pip uninstall green -y
    - pip uninstall python-termstyle -y

tag_pip-install:
  stage: tag_init
  when: always
  only:
    - tags
  script:
    - pip install wafer_map
    - pip install build-reqs/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl
    - pip install build-reqs/douglib-1.0.10-py3-none-any.whl
    - pip install green

tag_bundle:
  stage: tag_deploy
  when: on_success
  only:
    - tags
  script:
    - python build_exe.py build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - build/exe.win-amd64-3.4/
      - dist/*.whl

tag_clean-up:
  stage: tag_cleanup
  when: always
  only:
    - tags
  script:
    - pip uninstall wafer_map -y
    - pip uninstall wxPython-Phoenix -y
    - pip uninstall douglib -y
    - pip uninstall green -y
    - pip uninstall python-termstyle -y
